language: python
python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  - "3.4"
install:
    - "pip install -r requirements.txt --use-mirrors"
script:
    - "cd ./vim_snippets_paster && py.test -q"
